version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: telegrambackendapp:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - VIRTUAL_HOST=backend.hozyainduhi.ru
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=backend.hozyainduhi.ru
    volumes:
      - ./images:/app/images
      - ./photos:/app/photos
    expose:
      - "80"
networks:
  default:
    external:
      name: nginx-proxy_default